name: Learn basics of GitHub Action

on:
  push:
    branches:
      - master

jobs:
  install-java:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest

    steps:
      - name: Install Java
        run: |
          apk add --no-cache openjdk11

      - name: Print Java version
        run: java -version

      

 
