name: Learn basic of GitHub Action

on:
  push:
    branches:
      - main

jobs:
  helloworld1:
    runs-on: ubuntu-latest
    container:
       image: alpine:latest

    steps:
      - name: print hello
        run: cat /etc/os-release

      

 
